// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM0wbZ9mv5CFl25G6xwkl-267zecNzDlY',
    appId: '1:301771516186:web:13ba081043fe24331ce4a3',
    messagingSenderId: '301771516186',
    projectId: 'ecommerce-b322d',
    authDomain: 'ecommerce-b322d.firebaseapp.com',
    storageBucket: 'ecommerce-b322d.firebasestorage.app',
    measurementId: 'G-RMK535JTQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxfcoxk6SjxejNFJreVI9vxsxsg6QjaQs',
    appId: '1:301771516186:android:91a943afa756f7861ce4a3',
    messagingSenderId: '301771516186',
    projectId: 'ecommerce-b322d',
    storageBucket: 'ecommerce-b322d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCigXESOAzn1CL-Fe3Zp3EJFFOzHtydddw',
    appId: '1:301771516186:ios:c9e51b0e5f221b9a1ce4a3',
    messagingSenderId: '301771516186',
    projectId: 'ecommerce-b322d',
    storageBucket: 'ecommerce-b322d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCigXESOAzn1CL-Fe3Zp3EJFFOzHtydddw',
    appId: '1:301771516186:ios:c9e51b0e5f221b9a1ce4a3',
    messagingSenderId: '301771516186',
    projectId: 'ecommerce-b322d',
    storageBucket: 'ecommerce-b322d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM0wbZ9mv5CFl25G6xwkl-267zecNzDlY',
    appId: '1:301771516186:web:b9b352561d2e842d1ce4a3',
    messagingSenderId: '301771516186',
    projectId: 'ecommerce-b322d',
    authDomain: 'ecommerce-b322d.firebaseapp.com',
    storageBucket: 'ecommerce-b322d.firebasestorage.app',
    measurementId: 'G-RVK6RJ02TJ',
  );
}
